# This is a basic workflow to help you get started with Actions

name: Build UEFI for a given platform

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

# Indicate that we are running in CI
env:
  WM_CI_BUILD: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs called "setup" and "build"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.matrix.outputs.value }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - id: matrix
        run: |
          search_list="$(find ./Platforms/${{ inputs.platform }} -maxdepth 2 -wholename "*/Device/qcom-qrd*"  -printf "\"%f\", ")"
          if [ -z "$search_list" ]; then
            search_list="$(find ./Platforms/${{ inputs.platform }} -maxdepth 2 -wholename "*/Device/qcom-mtp*"  -printf "\"%f\", ")"
            if [ -z "$search_list" ]; then
              search_list="$(find ./Platforms/${{ inputs.platform }} -maxdepth 2 -wholename "*/Device/qcom-hdk*"  -printf "\"%f\", ")"
            fi
          fi
          echo "value=[$search_list]" >> $GITHUB_OUTPUT

  build:
    strategy:
      matrix:
        target: ${{fromJSON(needs.setup.outputs.matrix)}}

    needs: setup
    uses: woa-msmnile/msmnilePkg/.github/workflows/build_device.yml@main
    with:
      target: ${{ matrix.target }}
    secrets: inherit
